### PR TITLE
DB-432 Build: fix mar signing on Windows / Linux

### PR DESCRIPTION
**Pull request by chrmod**
Implements: https://cliqztix.atlassian.net/browse/DB-432

### CODE REVIEW

**Comment by alver-cliqz** [comment]
I think it's better create two different script. One for create a MAR file, another to upload. Also this could help us with improve PR build process

**Comment by maxim-cliqz** [comment]
Looks OK except paths because the only way to be sure with those is to run and check the outcome.

**Comment by alver-cliqz** [comment]
retest this please

**Comment by alver-cliqz** [comment]
retest this please

**Comment by alver-cliqz** [comment]
retest this please

**Comment by alver-cliqz** [comment]
retest this please

**Comment by alver-cliqz** [comment]
retest this please

**Comment by chrmod** [comment]
retest this please

**Comment by alver-cliqz** [comment]
retest this please

**Comment by luciancor** [comment]
retest this please

**Comment by chrmod** [comment]
retest this please

**Comment by alver-cliqz** [comment]
retest this please

**Comment by alver-cliqz** [comment]
retest this please

**Comment by alver-cliqz** [comment]
retest this please

**Comment by chrmod** [comment]
retest this please

**Comment by luciancor** [comment]
merging this knowing that MacOS still has some issues

**Pull request merged**
