### PR TITLE
BROWSER-64: Use own displayed version

### PR DESCRIPTION
**Pull request by maxim-cliqz**

### CODE REVIEW

**Comment by maxim-cliqz** [comment]
@alver-cliqz FYI

**Comment by alver-cliqz** [comment]
What about update request? Please check that it still use FF version for check update (mozilla-release\browser\app\profile\firefox.js, option pref("app.update.url")).

**Comment by maxim-cliqz** [comment]
I already checked. it queries URL built from this template `https://updatecheck.cliqz.com/update/3/%PRODUCT%/%VERSION%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/update.xml`

**Comment by chrmod** [comment]
That's a very clean solution. Please keep distribution version in sync:
https://github.com/cliqz-oss/browser-f/blob/master/repack/distribution/distribution.ini#L9

also this release shall be called 0.8.3 as the milestone

**Comment by maxim-cliqz** [comment]
retest this please

**Pull request merged**
