### PR TITLE
DB-624: make cliqz@cliqz.com a System Addon

### PR DESCRIPTION
**Pull request by chrmod**

### CODE REVIEW

**Comment by chrmod** [comment]
tested it on windows and linux, worked just fine.

We still need to wait for balrog update, but browser should be ready

**Comment by luciancor** [comment]
@chrmod is the mac builder down?

**Comment by luciancor** [comment]
retest this please

**Comment by alver-cliqz** [comment]
No, we still can face with problem of different xpi while building on Mac (because building doing twice).

**Pull request merged**
