### PR TITLE
Issue 84

### PR DESCRIPTION
**Pull request by alver-cliqz**
Merge with FF 43.
Ticket https://github.com/cliqz-oss/browser-f/issues/84

### CODE REVIEW

**Comment by chrmod** [comment]
Seems that CI host does not have required libraries to build browser-f towards Firefox 43. 

We should run bootstrap on all build machines. The simplest way is to 
```
curl https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py > bootstrap.py && python bootstrap.py
```
or just:
```
python ./mozilla-release/python/mozboot/bin/bootstrap.py
```

Would be perfect to have this procedure as a part of build scripts, but there are two problems:
* it requires root privileges
* it is interactive (maybe there is some command line argument to pass that will make it non-interactive)

Any opinions on that @alver-cliqz @maxim-cliqz ? How you updated build machines for chromium?

**Comment by chrmod** [comment]
@alver-cliqz can you please make PR title more meaningful. Also include original issue URL in PR description or in commit message so Github can track it automatically.

**Comment by alver-cliqz** [comment]
retest this please

**Comment by chrmod** [comment]
retest this please

**Pull request closed without merging**
